-- ============================================================
-- Cable TV Customer Management System - Database Schema
-- ============================================================

CREATE DATABASE IF NOT EXISTS cabletv_db;
USE cabletv_db;

-- ============================================================
-- USERS TABLE
-- ============================================================
CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    phone VARCHAR(15) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,          -- bcrypt hashed
    plan_id INT DEFAULT NULL,
    status ENUM('Active', 'Inactive') DEFAULT 'Inactive',
    is_admin TINYINT(1) DEFAULT 0,           -- 1 = admin, 0 = customer
    stb_number VARCHAR(50) DEFAULT NULL,     -- Set-top box serial number
    address TEXT DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- ============================================================
-- PLANS TABLE
-- ============================================================
CREATE TABLE IF NOT EXISTS plans (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    price DECIMAL(10,2) NOT NULL,
    duration_days INT DEFAULT 30,            -- Plan validity in days
    channels INT DEFAULT 0,                  -- Number of channels
    description TEXT DEFAULT NULL,
    is_active TINYINT(1) DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- PAYMENTS TABLE
-- ============================================================
CREATE TABLE IF NOT EXISTS payments (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    plan_id INT NOT NULL,
    amount DECIMAL(10,2) NOT NULL,
    razorpay_order_id VARCHAR(100) DEFAULT NULL,
    razorpay_payment_id VARCHAR(100) DEFAULT NULL,
    status ENUM('Pending', 'Success', 'Failed') DEFAULT 'Pending',
    payment_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (plan_id) REFERENCES plans(id) ON DELETE CASCADE
);

-- ============================================================
-- SEED: DEFAULT PLANS
-- ============================================================
INSERT INTO plans (name, price, duration_days, channels, description) VALUES
('Kids Plan',        100.00, 30,  80,  'Cartoons, educational & family-friendly channels'),
('Sports Plan',      150.00, 30,  60,  'All major sports: Cricket, Football, Tennis & more'),
('Movies Plan',      200.00, 30,  90,  'Bollywood, Hollywood & regional movie channels'),
('Basic Plan',        79.00, 30,  50,  'Essential news, entertainment & regional channels'),
('Starter Pack',      49.00, 30,  35,  'Perfect for light viewers – news & general entertainment'),
('Premium Plan',     299.00, 30, 200,  'All channels including premium HD & OTT add-ons'),
('South Special',    120.00, 30,  75,  'Tamil, Telugu, Kannada & Malayalam channels'),
('News Pack',         89.00, 30,  40,  'All national & international news channels 24/7'),
('HD Sports Ultra',  350.00, 30,  70,  'All sports in Full HD + Live streaming access'),
('Family Combo',     249.00, 30, 160,  'Kids + Movies + Sports – best value for families'),
('Mini Pack',         35.00, 15,  25,  '15-day short plan – DD Free Dish + basic channels'),
('Annual Mega Pack', 999.00,365, 250,  'Full year subscription with all premium channels');

-- ============================================================
-- SEED: DEFAULT ADMIN USER
-- Password: admin123 (bcrypt hash generated by app on first run)
-- ============================================================
-- Admin is inserted programmatically by app.py on first run.
-- See app.py → create_default_admin()

-- ============================================================
-- SEED: SAMPLE CUSTOMERS (for demo)
-- Password for all: password123
-- ============================================================
-- Sample users are inserted programmatically by app.py on first run.
